def get_country_data():
    return {
        "australia": "au.png",
        "united kingdom": "gb.png",
        "germany": "de.png",
        "france": "fr.png",
        "united states": "us.png",
        "afghanistan": "af.png",
        "albania": "al.png",
        "algeria": "dz.png",
        "andorra": "ad.png",
        "angola": "ao.png",
        "antigua and barbuda": "ag.png",
        "argentina": "ar.png",
        "armenia": "am.png",
        "austria": "at.png",
        "azerbaijan": "az.png",
        "bahamas": "bs.png",
        "bahrain": "bh.png",
        "bangladesh": "bd.png",
        "barbados": "bb.png",
        "belarus": "by.png",
        "belgium": "be.png",
        "belize": "bz.png",
        "benin": "bj.png",
        "bhutan": "bt.png",
        "bolivia": "bo.png",
        "bosnia and herzegovina": "ba.png",
        "botswana": "bw.png",
        "brazil": "br.png",
        "brunei": "bn.png",
        "bulgaria": "bg.png",
        "burkina faso": "bf.png",
        "burundi": "bi.png",
        "cabo verde": "cv.png",
        "cambodia": "kh.png",
        "cameroon": "cm.png",
        "canada": "ca.png",
        "cayman islands": "ky.png",
        "central african republic": "cf.png",
        "chad": "td.png",
        "chile": "cl.png",
        "china": "cn.png",
        "colombia": "co.png",
        "comoros": "km.png",
        "congo, democratic republic of the": "cd.png",
        "congo, republic of the": "cg.png",
        "costa rica": "cr.png",
        "croatia": "hr.png",
        "cuba": "cu.png",
        "cyprus": "cy.png",
        "czech republic": "cz.png",
        "denmark": "dk.png",
        "djibouti": "dj.png",
        "dominica": "dm.png",
        "dominican republic": "do.png",
        "ecuador": "ec.png",
        "egypt": "eg.png",
        "el salvador": "sv.png",
        "equatorial guinea": "gq.png",
        "eritrea": "er.png",
        "estonia": "ee.png",
        "eswatini": "sz.png",
        "ethiopia": "et.png",
        "fiji": "fj.png",
        "finland": "fi.png",
        "gabon": "ga.png",
        "gambia": "gm.png",
        "georgia": "ge.png",
        "ghana": "gh.png",
        "greece": "gr.png",
        "grenada": "gd.png",
        "guatemala": "gt.png",
        "guinea": "gn.png",
        "guinea-bissau": "gw.png",
        "guyana": "gy.png",
        "haiti": "ht.png",
        "honduras": "hn.png",
        "hong kong": "hk.png",
        "hungary": "hu.png",
        "iceland": "is.png",
        "india": "in.png",
        "indonesia": "id.png",
        "iran": "ir.png",
        "iraq": "iq.png",
        "ireland": "ie.png",
        "israel": "il.png",
        "italy": "it.png",
        "ivory coast": "ci.png",
        "jamaica": "jm.png",
        "japan": "jp.png",
        "jordan": "jo.png",
        "kazakhstan": "kz.png",
        "kenya": "ke.png",
        "kiribati": "ki.png",
        "north korea": "kp.png",
        "south korea": "kr.png",
        "kosovo": "xk.png",
        "kuwait": "kw.png",
        "kyrgyzstan": "kg.png",
        "laos": "la.png",
        "latvia": "lv.png",
        "lebanon": "lb.png",
        "lesotho": "ls.png",
        "liberia": "lr.png",
        "libya": "ly.png",
        "liechtenstein": "li.png",
        "lithuania": "lt.png",
        "luxembourg": "lu.png",
        "madagascar": "mg.png",
        "malawi": "mw.png",
        "malaysia": "my.png",
        "maldives": "mv.png",
        "mali": "ml.png",
        "malta": "mt.png",
        "marshall islands": "mh.png",
        "mauritania": "mr.png",
        "mauritius": "mu.png",
        "mexico": "mx.png",
        "micronesia": "fm.png",
        "moldova": "md.png",
        "monaco": "mc.png",
        "mongolia": "mn.png",
        "montenegro": "me.png",
        "morocco": "ma.png",
        "mozambique": "mz.png",
        "myanmar": "mm.png",
        "namibia": "na.png",
        "nauru": "nr.png",
        "nepal": "np.png",
        "netherlands": "nl.png",
        "new zealand": "nz.png",
        "nicaragua": "ni.png",
        "niger": "ne.png",
        "nigeria": "ng.png",
        "north macedonia": "mk.png",
        "norway": "no.png",
        "oman": "om.png",
        "pakistan": "pk.png",
        "palau": "pw.png",
        "panama": "pa.png",
        "papua new guinea": "pg.png",
        "paraguay": "py.png",
        "peru": "pe.png",
        "philippines": "ph.png",
        "poland": "pl.png",
        "portugal": "pt.png",
        "qatar": "qa.png",
        "romania": "ro.png",
        "russia": "ru.png",
        "rwanda": "rw.png",
        "saint kitts and nevis": "kn.png",
        "saint lucia": "lc.png",
        "saint vincent and the grenadines": "vc.png",
        "samoa": "ws.png",
        "san marino": "sm.png",
        "sao tome and principe": "st.png",
        "saudi arabia": "sa.png",
        "senegal": "sn.png",
        "serbia": "rs.png",
        "seychelles": "sc.png",
        "sierra leone": "sl.png",
        "singapore": "sg.png",
        "slovakia": "sk.png",
        "slovenia": "si.png",
        "solomon islands": "sb.png",
        "somalia": "so.png",
        "south africa": "za.png",
        "south sudan": "ss.png",
        "spain": "es.png",
        "sri lanka": "lk.png",
        "sudan": "sd.png",
        "suriname": "sr.png",
        "sweden": "se.png",
        "switzerland": "ch.png",
        "syria": "sy.png",
        "taiwan": "tw.png",
        "tajikistan": "tj.png",
        "tanzania": "tz.png",
        "thailand": "th.png",
        "timor-leste": "tl.png",
        "togo": "tg.png",
        "tonga": "to.png",
        "trinidad and tobago": "tt.png",
        "tunisia": "tn.png",
        "turkey": "tr.png",
        "turkmenistan": "tm.png",
        "tuvalu": "tv.png",
        "uganda": "ug.png",
        "ukraine": "ua.png",
        "united arab emirates": "ae.png",
        "uruguay": "uy.png",
        "uzbekistan": "uz.png",
        "vanuatu": "vu.png",
        "vatican city": "va.png",
        "venezuela": "ve.png",
        "vietnam": "vn.png",
        "yemen": "ye.png",
        "zambia": "zm.png",
        "zimbabwe": "zw.png"
    }

def get_country_flag(country):
    if not country:
        return "unknown.png"

    code = country.strip().lower()

    # If it's a 2-letter code like "au" or "ae", use directly
    if len(code) == 2:
        return f"{code}.png"

    # Otherwise look up from name map (if you have one)
    country_map = get_country_data()  # if using full names
    return country_map.get(code, "unknown.png")

def get_country_list():
    return [{"name": name} for name in get_country_data().keys()]